### ISSUE TITLE
XML Header in antlers template is missing

### ISSUE THREAD

**Issue by steffenschmidt** [pecotamic/sitemap#15]
I used an antlers template instead of a blade. This is my code:

```
{{ xml_header }}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  ...
</urlset>
```

This is my expected output for `/sitemap.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset>
  ...
</urlset>
```

This is the output I got for `/sitemap.xml`:

```
<urlset>
  ...
</urlset>
```

The complete xml tag is missing. After switching back to the blade template I found out that there is also output of a xml header.

Any idea how I can fix this?

**Comment by werner-freytag** [comment]
Fixed in release 1.2.7

**Comment by steffenschmidt** [comment]
The release 1.2.7 does not fix this issue for me. Anything I have to change beside updating the package?

**Comment by werner-freytag** [comment]
Maybe a caching issue?

**Comment by werner-freytag** [comment]
On my testing device the xml tag is there when I use your antlers template and fetch it with `curl`.

I saw that you forked the original repo. Are you sure that the updated version is used? Could the old version be in use for some reason?
